language: java
jdk:
    - oraclejdk7
install:
    - mvn install -DskipTests=true
script:
    - mvn clean compile -DskipTests=true -Dmaven.javadoc.skip=true
cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2
